### ISSUE TITLE
Fail to extract names.dmp from taxdump

### ISSUE THREAD

**Issue by Adamtaranto** [kdmurray91/lpipy#1]
Taxdump.tar.gz is downloaded to a user directory, it contains the names and nodes files. 

```
Downloading http://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz to /home/adam/.local/var/lpi/taxdump.tar.gz
```

Program exits after trying to find and un-tar 'names.dmp' (looking in local directory??) from line 231 of taxonomy.py

```
Downloaded http://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz
We have a valid Taxdump file
GI to tax prot file found, calculating checksum
We have a valid gi_taxid_prot file
GI to tax nucl file found, calculating checksum
We have a valid gi_taxid_nucl file
Traceback (most recent call last):
  File "./lpipy/misc/demo.py", line 8, in <module>
    db = NCBITaxonomyDB()
  File "/usr/local/lib/python2.7/dist-packages/lpi-0_untagged.11.gd0f1d6a-py2.7.egg/lpi/taxonomy.py", line 99, in __init__
    self._connect()
  File "/usr/local/lib/python2.7/dist-packages/lpi-0_untagged.11.gd0f1d6a-py2.7.egg/lpi/taxonomy.py", line 117, in _connect
    self._create_db()
  File "/usr/local/lib/python2.7/dist-packages/lpi-0_untagged.11.gd0f1d6a-py2.7.egg/lpi/taxonomy.py", line 164, in _create_db
    self._load_db()
  File "/usr/local/lib/python2.7/dist-packages/lpi-0_untagged.11.gd0f1d6a-py2.7.egg/lpi/taxonomy.py", line 231, in _load_db
    for taxon in dmpfile('names.dmp'):
  File "/usr/local/lib/python2.7/dist-packages/lpi-0_untagged.11.gd0f1d6a-py2.7.egg/lpi/taxonomy.py", line 220, in dmpfile
    with tar.extractfile(filename) as fh:
AttributeError: __exit__
```

**Comment by kdm9** [comment]
That's because the tarfile object seems not to support the context manager protocol, which is very weird. Which python version?

**Comment by Adamtaranto** [comment]
v2.7.6

**Comment by Adamtaranto** [comment]
Solved: Use python3

**Comment by kdm9** [comment]
OK, I'll reopen this as I'd like it to work with both python versions. But as a workaround for now, I'm glad python3 works.
