### ISSUE TITLE
Random tuple instead of int as taxid in taxonomy.py

### ISSUE THREAD

**Issue by Adamtaranto** [kdmurray91/lpipy#4]
Added a print statement to find taxid that was killing taxon_parents()

``` python
def taxon_parents(self, taxid):
        c = self._db.cursor()
        print(taxid)
        qry = c.execute("""SELECT parents.parent, taxa.rank, taxa.name
                           FROM parents
                           INNER JOIN taxa ON taxa.taxid = parents.parent
                           WHERE parents.taxid = ?
                           ORDER BY parents.level;""",
                        (taxid, ))
        for parent, rank, name in qry:
            yield (parent, rank, name)
```

See line "(6087,)" reported by print(taxid) right before error. Looks like a tuple for some reason??

``` bash
43151
85433
209169
34613
215358
6945
10224
176946
353153
(6087,)
Traceback (most recent call last):
  File "./lpipy/misc/demo.py", line 49, in <module>
    tax = db.sequence_lineage(gi, ALL_RANKS)
  File "/usr/local/lib/python3.4/dist-packages/lpi-0_untagged.11.gd0f1d6a.dirty-py3.4.egg/lpi/taxonomy.py", line 361, in sequence_lineage
    return self.taxon_lineage(taxid)
  File "/usr/local/lib/python3.4/dist-packages/lpi-0_untagged.11.gd0f1d6a.dirty-py3.4.egg/lpi/taxonomy.py", line 354, in taxon_lineage
    for taxid, rank, name in self.taxon_parents(taxid):
  File "/usr/local/lib/python3.4/dist-packages/lpi-0_untagged.11.gd0f1d6a.dirty-py3.4.egg/lpi/taxonomy.py", line 346, in taxon_parents
    (taxid, ))
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
```

**Comment by kdm9** [comment]
Ok, where are you getting the taxids from. Can you please upload a minimal failing example?

**Comment by Adamtaranto** [comment]
Resources all downloaded automatically. Have sent the tab result file that causes the error.

**Comment by kdm9** [comment]
Can you put the script up as a gist, or are you just using demo.py
